# Generated by Django 2.1.7 on 2019-03-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
