# Generated by Django 2.1.7 on 2019-03-07 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0002_auto_20190303_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='problem',
        ),
        migrations.DeleteModel(
            name='Contest',
        ),
    ]
