# Generated by Django 2.1.7 on 2019-03-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0003_auto_20190306_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='description',
            field=models.TextField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='solution',
            field=models.TextField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
