# Generated by Django 2.1.7 on 2019-03-07 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0004_auto_20190306_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(max_length=10000)),
                ('solution', models.TextField(max_length=10000)),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='solution',
        ),
        migrations.AddField(
            model_name='part',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jam.Problem'),
        ),
    ]
