# Generated by Django 2.1.7 on 2019-03-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jam', '0005_auto_20190314_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(),
        ),
    ]
