# Generated by Django 2.1.7 on 2019-03-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0009_remove_submission_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='correct',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
