# Generated by Django 2.1.7 on 2019-03-11 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id',
                 models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                  verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('input', models.TextField(blank=True, max_length=10000)),
                ('solution', models.TextField(blank=True, max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id',
                 models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                  verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id',
                 models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                  verbose_name='ID')),
                ('submission', models.TextField(max_length=10000)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           to='contest.Part')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='contest.Problem'),
        ),
    ]
