# Generated by Django 2.1.7 on 2019-03-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contest', '0002_auto_20190313_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
