# Generated by Django 2.1.7 on 2019-03-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contest', '0003_submission_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
