# Generated by Django 2.1.7 on 2019-03-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contest', '0004_part_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='input',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission',
            field=models.TextField(),
        ),
    ]
