# Generated by Django 2.1.7 on 2019-03-15 15:30

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contest', '0006_auto_20190315_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
    ]
