# Generated by Django 2.2.6 on 2019-10-12 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_auto_20190315_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='part',
        ),
        migrations.AddField(
            model_name='problem',
            name='input',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contest.Problem'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
