# Generated by Django 2.2.6 on 2019-10-23 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_auto_20191023_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='submission',
        ),
    ]
